**CONTENT BASED RECOMMENDER SYSTEM**

Project flow -

Data -> Preprocessing -> model -> website -> deployment

In [1]:
from google.colab import files
upload = files.upload()

KeyboardInterrupt: ignored

In [2]:
from google.colab import files
upload = files.upload()

In [3]:
import numpy as np
import pandas as pd

In [4]:
movies = pd.read_csv('/content/tmdb_5000_movies.csv')
credits = pd.read_csv('/content/tmdb_5000_credits.csv')

In [6]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [7]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [8]:
credits.head(1)['cast'].values

array(['[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'],
      dtype=object)

Merging the dataframes

In [9]:
movies = pd.DataFrame(movies)
credits = pd.DataFrame(credits)

In [10]:
movie = pd.merge(movies,credits)

In [12]:
movie.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [13]:
movie['original_language'].value_counts()

en    4510
fr      70
es      32
zh      27
de      27
hi      19
ja      16
it      14
ko      12
cn      12
ru      11
pt       9
da       7
sv       5
nl       4
fa       4
th       3
he       3
ta       2
cs       2
ro       2
id       2
ar       2
vi       1
sl       1
ps       1
no       1
ky       1
hu       1
pl       1
af       1
nb       1
tr       1
is       1
xx       1
te       1
el       1
Name: original_language, dtype: int64

In [15]:
movie['overview']

0       In the 22nd century, a paraplegic Marine is di...
1       Captain Barbossa, long believed to be dead, ha...
2       A cryptic message from Bond’s past sends him o...
3       Following the death of District Attorney Harve...
4       John Carter is a war-weary, former military ca...
                              ...
4804    El Mariachi just wants to play his guitar and ...
4805    A newlywed couple's honeymoon is upended by th...
4806    "Signed, Sealed, Delivered" introduces a dedic...
4807    When ambitious New York attorney Sam is sent t...
4808    Ever since the second grade when he first saw ...
Name: overview, Length: 4809, dtype: object

In [14]:
movie.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 901.7+ KB

Columns to be kept
1. genres
2. id
3. keywords
4. title
5. overview
6. cast
7. crew

In [17]:
movies = movie[['movie_id', 'genres', 'keywords','title','overview','cast','crew']]

In [20]:
movies.isnull().sum()

movie_id    0
genres      0
keywords    0
title       0
overview    0
cast        0
crew        0
dtype: int64

In [19]:
movies.dropna(inplace=True)

/usr/local/lib/python3.7/dist-packages/pandas/util/_decorators.py:311: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)

In [22]:
movies.duplicated().sum()

0

In [23]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [24]:
import ast

In [25]:
def convert(obj):
  L = []
  for i in ast.literal_eval(obj):
    L.append(i['name'])
  return L

In [26]:
movies['genres'] = movies['genres'].apply(convert)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [27]:
movies.head()

,movie_id,genres,keywords,title,overview,cast,crew
0,19995,"[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,"[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",Spectre,A cryptic message from Bond’s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,"[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",John Carter,"John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [29]:
movies['keywords']=movies['keywords'].apply(convert)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [31]:
def convert3(obj):
  L = []
  counter = 0
  for i in ast.literal_eval(obj):
    if counter != 3:
      L.append(i['name'])
      counter+=1
    else:
      break
  return L

In [32]:
movies['cast']=movies['cast'].apply(convert3)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [34]:
movies.head()

,movie_id,genres,keywords,title,overview,cast,crew
0,19995,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",Spectre,A cryptic message from Bond’s past sends him o...,"[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",The Dark Knight Rises,Following the death of District Attorney Harve...,"[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...",John Carter,"John Carter is a war-weary, former military ca...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [35]:
def fetch_director(obj):
  L = []
  for i in ast.literal_eval(obj):
    if i['job']=='Director':
      L.append(i['name'])
      break
  return L

In [37]:
movies['crew']=movies['crew'].apply(fetch_director)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [38]:
movies.head()

,movie_id,genres,keywords,title,overview,cast,crew
0,19995,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",Spectre,A cryptic message from Bond’s past sends him o...,"[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",The Dark Knight Rises,Following the death of District Attorney Harve...,"[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...",John Carter,"John Carter is a war-weary, former military ca...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [40]:
movies['overview']=movies['overview'].apply(lambda x:x.split())

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [41]:
movies.head()

,movie_id,genres,keywords,title,overview,cast,crew
0,19995,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...",Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...",Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...",John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

Applying a transformation upon the strings

In [44]:
movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [45]:
movies.head()

,movie_id,genres,keywords,title,overview,cast,crew
0,19995,"[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...",Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,"[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...",Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...",Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...",The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,"[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...",John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [46]:
movies['tags'] = movies['overview']+movies['genres']+movies['keywords']+movies['cast']+movies['crew']

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [47]:
movies.head()

,movie_id,genres,keywords,title,overview,cast,crew,tags
0,19995,"[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...",Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,"[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...",Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...",Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...",The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,"[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...",John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [48]:
new_df = movies[['movie_id','title','tags']]

In [49]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [52]:
new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [53]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [54]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [55]:
new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [56]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

*Vectorization*

In [72]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features=5000 , stop_words='english')

In [73]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [74]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [75]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0])

In [76]:
cv.get_feature_names()

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '17th',
 '18',
 '18th',
 '18thcenturi',
 '19',
 '1910',
 '1920',
 '1930',
 '1940',
 '1944',
 '1950',
 '1950s',
 '1960',
 '1960s',
 '1970',
 '1970s',
 '1971',
 '1974',
 '1976',
 '1980',
 '1985',
 '1990',
 '1999',
 '19th',
 '19thcenturi',
 '20',
 '200',
 '2003',
 '2009',
 '20th',
 '21st',
 '23',
 '24',
 '25',
 '30',
 '300',
 '3d',
 '40',
 '50',
 '500',
 '60',
 '70',
 '80',
 'aaron',
 'aaroneckhart',
 'abandon',
 'abduct',
 'abigailbreslin',
 'abil',
 'abl',
 'aboard',
 'abov',
 'abus',
 'academ',
 'academi',
 'accept',
 'access',
 'accid',
 'accident',
 'acclaim',
 'accompani',
 'accomplish',
 'account',
 'accus',
 'ace',
 'achiev',
 'acquaint',
 'act',
 'action',
 'actionhero',
 'activ',
 'activist',
 'activities',
 'actor',
 'actress',
 'actual',
 'ad',
 'adam',
 'adamsandl',
 'adamshankman',
 'adapt',
 'add',
 'addict',
 'adjust',
 'admir',
 'admit',
 'adolesc',
 'adopt',
 'ador',
 'adrienbrodi',
 'adult',
 'adultanim',
 'adulteri',
 'adulthood',
 'advanc',
 'adventur',
 'adventure',
 'adventures',
 'advertis',
 'advic',
 'advis',
 'affair',
 'affect',
 'afghanistan',
 'africa',
 'african',
 'africanamerican',
 'aftercreditssting',
 'afterlif',
 'aftermath',
 'ag',
 'age',
 'agediffer',
 'agenc',
 'agency',
 'agenda',
 'agent',
 'agents',
 'aggress',
 'ago',
 'agre',
 'ahead',
 'aid',
 'aidanquinn',
 'ail',
 'aim',
 'air',
 'airplan',
 'airplanecrash',
 'airport',
 'aka',
 'al',
 'alabama',
 'alan',
 'alaska',
 'albert',
 'alcatraz',
 'alcohol',
 'alecbaldwin',
 'alex',
 'alexkendrick',
 'alfredhitchcock',
 'alfredmolina',
 'ali',
 'alic',
 'alice',
 'alien',
 'alieninvas',
 'alienlife',
 'alienplanet',
 'aliens',
 'alik',
 'aliv',
 'alive',
 'allen',
 'alli',
 'allianc',
 'allow',
 'alon',
 'alongsid',
 'alpacino',
 'alpha',
 'alreadi',
 'alter',
 'altern',
 'alway',
 'alyssa',
 'alzheimer',
 'amanda',
 'amandapeet',
 'amandaseyfri',
 'amateur',
 'amaz',
 'amazon',
 'ambassador',
 'ambit',
 'ambiti',
 'ambul',
 'ambush',
 'america',
 'american',
 'americanabroad',
 'americancivilwar',
 'americanfootbal',
 'americanfootballplay',
 'amid',
 'amidst',
 'amnesia',
 'amp',
 'amsterdam',
 'amus',
 'amusementpark',
 'amy',
 'amyadam',
 'amysmart',
 'ana',
 'anakin',
 'analyst',
 'anarchiccomedi',
 'ancient',
 'ancientrom',
 'ancientworld',
 'anderson',
 'andi',
 'andiemacdowel',
 'andrew',
 'android',
 'andy',
 'andygarcía',
 'angel',
 'angela',
 'angelabassett',
 'angeles',
 'angelinajoli',
 'anger',
 'angle',
 'angri',
 'ani',
 'anim',
 'animalattack',
 'animalhorror',
 'animals',
 'anjelicahuston',
 'ann',
 'anna',
 'annafari',
 'annakendrick',
 'anne',
 'annehathaway',
 'annemoss',
 'annetteben',
 'anni',
 'annie',
 'anniversari',
 'announc',
 'annual',
 'anonym',
 'anoth',
 'answer',
 'ant',
 'antholog',
 'anthoni',
 'anthonyanderson',
 'anthonyhopkin',
 'anthropomorph',
 'anti',
 'antic',
 'antihero',
 'antiqu',
 'antoinefuqua',
 'antoniobandera',
 'antonyelchin',
 'anyon',
 'anyth',
 'apart',
 'apartheid',
 'apartment',
 'ape',
 'apocalyps',
 'apocalypse',
 'apocalypt',
 'appar',
 'appear',
 'appl',
 'apple',
 'appoint',
 'appreci',
 'apprentic',
 'approach',
 'april',
 'aquarium',
 'arab',
 'arch',
 'archaeologist',
 'archeolog',
 'archer',
 'architect',
 'arctic',
 'area',
 'aren',
 'arena',
 'argument',
 'aris',
 'aristocrat',
 'arm',
 'armi',
 'armor',
 'armsdeal',
 'army',
 'arnold',
 'arnoldschwarzenegg',
 'arrang',
 'arrangedmarriag',
 'arrest',
 'arriv',
 'arrog',
 'art',
 'arthur',
 'artifact',
 'artifici',
 'artificialintellig',
 'artist',
 'ash',
 'ashley',
 'ashleyjudd',
 'ashtonkutch',
 'asia',
 'asian',
 'asid',
 'ask',
 'aspect',
 'aspir',
 'assassin',
 'assault',
 'assembl',
 'assign',
 'assist',
 'assistant',
 'associ',
 'assum',
 'asteroid',
 'astronaut',
 'asylum',
 'atheist',
 'athlet',
 'atom',
 'atomicbomb',
 'attack',
 'attacks',
 'attempt',
 'attend',
 'attent',
 'attic',
 'attitud',
 'attorney',
 'attract',
 'auction',
 'audienc',
 'audit',
 'august',
 'aunt',
 'austin',
 'australia',
 'australian',
 'author',
 'autism',
 'auto',
 'automobilerac',
 'aveng',
 'averag',
 'avoid',
 'await',
 'awak',
 'awaken',
 'awar',
 'award',
 'away',
 'awkward',
 'awri',
 'awry',
 'ax',
 'babe',
 'babi',
 'baby',
 'bachelor',
 'backdrop',
 'background',
 'backpack',
 'bad',
 'bag',
 'bahama',
 'bail',
 'balanc',
 'ball',
 'ballet',
 'balloon',
 'baltimor',
 'ban',
 'band',
 'bandit',
 'bangkok',
 'banish',
 'bank',
 'banker',
 'bankrobb',
 'bankrobberi',
 'bar',
 'barbrastreisand',
 'bare',
 'bargain',
 'barn',
 'barney',
 'baron',
 'barri',
 'barrylevinson',
 'barrysonnenfeld',
 'bas',
 'base',
 'basebal',
 'basedoncomicbook',
 'basedongraphicnovel',
 'basedonnovel',
 'basedonplay',
 'basedonstagemus',
 'basedontrueev',
 'basedontruestori',
 'basedontvseri',
 'basedonvideogam',
 'basedonyoungadultnovel',
 'basement',
 'basketbal',
 'basketball',
 'bat',
 'batman',
 'battl',
 'battle',
 'battlefield',
 'bay',
 'beach',
 'beam',
 'bear',
 'beard',
 'beast',
 'beat',
 'beauti',
 'beautiful',
 'beautifulwoman',
 'beauty',
 'becam',
 'becaus',
 'becki',
 'becom',
 'becominganadult',
 'bed',
 'bedroom',
 'bee',
 'beer',
 'befor',
 'befriend',
 'began',
 'begin',
 'begins',
 'behavior',
 'belief',
 'believ',
 'bell',
 'bella',
 'belong',
 'belov',
 'ben',
 'benaffleck',
 'bend',
 'beneath',
 'benefit',
 'benfost',
 'beniciodeltoro',
 'benjamin',
 'benjaminbratt',
 'benkingsley',
 'bennett',
 'benstil',
 'bent',
 'berlin',
 'best',
 'bestfriend',
 'bestfriendsinlov',
 'bet',
 'beth',
 'betray',
 'bettemidl',
 'better',
 'betti',
 'beverli',
 'bibl',
 'bid',
 'big',
 'bigger',
 'biggest',
 'bike',
 'biker',
 'bikini',
 'billhad',
 'billi',
 'billionair',
 'billmurray',
 'billnighi',
 'billpaxton',
 'billpullman',
 'billybobthornton',
 'billycrudup',
 'billycryst',
 'biographi',
 'biolog',
 'bird',
 'birth',
 'birthday',
 'bisexu',
 'bishop',
 'bit',
 'bite',
 'bitter',
 'bizarr',
 'black',
 'blackmag',
 'blackmail',
 'blackpeopl',
 'blacksmith',
 'blade',
 'blame',
 'blend',
 'blind',
 'bliss',
 'blizzard',
 'block',
 'blond',
 'blood',
 'bloodi',
 'bloodsplatt',
 'bloodthirsti',
 'blow',
 'blue',
 'board',
 'boardingschool',
 'boat',
 'bob',
 'bobbi',
 'bobbyfarrelli',
 'bobhoskin',
 'bodi',
 'body',
 'bodyguard',
 'bold',
 'bollywood',
 'bomb',
 'bond',
 'bone',
 'book',
 'border',
 'bore',
 'boredom',
 'born',
 'boss',
 'boston',
 'botch',
 'bound',
 'boundari',
 'bounti',
 'bountyhunt',
 'bout',
 'box',
 'boxer',
 'boy',
 'boyfriend',
 'boys',
 'bradleycoop',
 'bradpitt',
 'brain',
 'brainwash',
 'brand',
 'brandon',
 'brave',
 'braveri',
 'brazil',
 'brazilian',
 'break',
 'breakdown',
 'breast',
 'breath',
 'breed',
 'brendanfras',
 'brendangleeson',
 'brent',
 'brettratn',
 'brian',
 'briandepalma',
 'bride',
 'bridesmaid',
 'bridg',
 'brief',
 'brielarson',
 'brien',
 'bright',
 'brilliant',
 'bring',
 'brink',
 'britain',
 'british',
 'britishsecretservic',
 'brittanymurphi',
 'broadcast',
 'broadway',
 'broke',
 'broken',
 'broker',
 'bronx',
 'brook',
 'brooklyn',
 'broom',
 'brothel',
 'brother',
 'brotherbrotherrelationship',
 'brothers',
 'brothersisterrelationship',
 'brought',
 'brown',
 'bruce',
 'brucegreenwood',
 'brucewilli',
 'brutal',
 'bryansing',
 'bu',
 'buck',
 'bud',
 'buddi',
 'buddy',
 'buddycomedi',
 'buddycop',
 'budget',
 'build',
 'building',
 'built',
 'bullet',
 'bulli',
 'bumbl',
 'bunch',
 'bunker',
 'bunni',
 'burglar',
 'buri',
 'burn',
 'bush',
 'busi',
 'business',
 'businessman',
 'bust',
 'butcher',
 'butler',
 'butt',
 'button',
 'buy',
 'buzz',
 'cabin',
 'caesar',
 'cage',
 'cairo',
 'cal',
 'california',
 'calvin',
 'camcord',
 'came',
 'camera',
 'cameraman',
 'camerondiaz',
 'camp',
 'campaign',
 'campbell',
 'campu',
 'canada',
 'canadian',
 'cancer',
 'candi',
 'candid',
 'canin',
 'cannib',
 'canuxploit',
 'capabl',
 'caper',
 'capit',
 'capt',
 'captain',
 'captiv',
 'captur',
 'capture',
 'car',
 'caraccid',
 'carchas',
 'carcrash',
 'card',
 'care',
 'career',
 'carefre',
 'caretak',
 'careymulligan',
 'caribbean',
 'carjourney',
 'carl',
 'carlagugino',
 'carmen',
 'carol',
 'carolina',
 'carrac',
 'carri',
 'carrie',
 'cartel',
 'carter',
 'cartoon',
 'caryelw',
 'case',
 'caseyaffleck',
 'cash',
 'casino',
 'cast',
 'castl',
 'cat',
 'cataclysm',
 'catastroph',
 'catch',
 'cateblanchett',
 'catherinedeneuv',
 'catherinekeen',
 'catherinezeta',
 'cathol',
 'catholic',
 'cattl',
 'caught',
 'caus',
 'cavalri',
 'cave',
 'cavemen',
 'celebr',
 'celebration',
 'cell',
 'cellphon',
 'cemeteri',
 'center',
 'centr',
 'central',
 'centuri',
 'centuries',
 'century',
 'ceo',
 'certain',
 'chad',
 'chain',
 'chainsaw',
 'challeng',
 'chamber',
 'champion',
 'championship',
 'chanc',
 'chance',
 'chang',
 'change',
 'changed',
 'changes',
 'channingtatum',
 'chao',
 'chaos',
 'chaotic',
 'chapter',
 'charact',
 'character',
 'characters',
 'charg',
 'charismat',
 'charl',
 'charli',
 'charlie',
 'charliesheen',
 'charlizetheron',
 'charm',
 'chart',
 'chase',
 'chauffeur',
 'chazzpalminteri',
 'cheat',
 'check',
 'cheerlead',
 'chef',
 'chemic',
 'cher',
 'chevychas',
 'chicago',
 'chicken',
 'chief',
 'child',
 'childabus',
 'childhero',
 'childhood',
 'childprodigi',
 'children',
 'chill',
 'chimp',
 'china',
 'chines',
 'chip',
 'chipmunk',
 'chiwetelejiofor',
 'chloe',
 'chloëgracemoretz',
 'chloësevigni',
 'chocol',
 'choic',
 'choice',
 'choos',
 'chosen',
 'chowyun',
 'chri',
 'chriscolumbu',
 'chriscoop',
 'chrisevan',
 'chrishemsworth',
 'chrisklein',
 'chrispin',
 'chrisrock',
 'christ',
 'christian',
 'christianbal',
 'christianslat',
 'christin',
 'christinaappleg',
 'christinaricci',
 'christma',
 'christmas',
 'christmasparti',
 'christmastre',
 'christoph',
 'christopherlambert',
 'christopherlloyd',
 'christophernolan',
 'christopherplumm',
 'christopherwalken',
 'christophwaltz',
 'chrisweitz',
 'chronicl',
 'chuck',
 'church',
 'cia',
 'ciaránhind',
 'cigarettesmok',
 'cillianmurphi',
 'cinema',
 'circl',
 'circu',
 'circuit',
 'circumst',
 'citi',
 'citizen',
 'city',
 'civil',
 'civilian',
 'civilwar',
 'claim',
 'clair',
 'clairedan',
 'claireforlani',
 'clan',
 'clark',
 'clash',
 'class',
 'classdiffer',
 'classic',
 'classmat',
 'classroom',
 'claudevandamm',
 'clay',
 'clean',
 'clear',
 'clerk',
 'clever',
 'client',
 'clients',
 'cliff',
 'climat',
 'climb',
 'clinteastwood',
 'cliveowen',
 'clock',
 'clone',
 'close',
 'closer',
 'cloud',
 'clown',
 'club',
 'clue',
 'clueless',
 'clutch',
 'coach',
 'coast',
 'cocain',
 'code',
 'coffin',
 'cohen',
 'col',
 'cold',
 'coldwar',
 'cole',
 'colin',
 'colinfarrel',
 'colinfirth',
 'collaps',
 'colleagu',
 'collect',
 'collector',
 'colleg',
 'college',
 'collid',
 'collis',
 'colombia',
 'colonel',
 'coloni',
 'color',
 'colorado',
 'coma',
 'combat',
 'combin',
 'come',
 'comeback',
 'comed',
 'comedi',
 'comedian',
 'comedy',
 'comet',
 'comfort',
 'comic',
 'coming',
 'comingofag',
 'comingout',
 'command',
 'commando',
 'commerci',
 'commiss',
 'commit',
 'common',
 'commun',
 'communist',
 'community',
 'compani',
 'companion',
 'company',
 'compet',
 'competit',
 'competition',
 'complet',
 'complex',
 'complic',
 'compos',
 'compuls',
 'comput',
 'computerviru',
 'conan',
 'concern',
 'concert',
 'concoct',
 'condit',
 'condition',
 'conduct',
 'confeder',
 'confess',
 'confid',
 'confin',
 'conflict',
 'confront',
 'confus',
 'congress',
 'conman',
 'connect',
 'connecticut',
 'connel',
 'connor',
 'conquer',
 'consequ',
 'consequences',
 'conserv',
 'consid',
 'conspir',
 'conspiraci',
 'conspiracy',
 'constant',
 'constantli',
 'construct',
 'consum',
 'contact',
 'contain',
 'contemporari',
 'contend',
 'content',
 'contest',
 'continu',
 'contract',
 'contractor',
 'control',
 'controversi',
 'convent',
 'converg',
 'convers',
 'convict',
 'convinc',
 'cook',
 ...]

Stemming - gives you the base word

In [67]:
import nltk

In [68]:
from nltk.stem.porter import PorterStemmer

ps = PorterStemmer()

In [69]:
def stem(text):
  y = []

  for i in text.split():
    y.append(ps.stem(i))
  
  return " ".join(y)

In [71]:
new_df['tags']=new_df['tags'].apply(stem)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In higher dimension, euclidean distance is a curse. Hence it is not used.
Cos angle is used as a parameter in higher dimensions.

In [77]:
from sklearn.metrics.pairwise import cosine_similarity

In [79]:
similarity = cosine_similarity(vectors)

In [82]:
sorted(list(enumerate(similarity[0])), reverse=True, key=lambda x:x[1])[1:6]

[(1216, 0.28676966733820225),
 (2409, 0.26901379342448517),
 (3730, 0.2605130246476754),
 (507, 0.255608593705383),
 (539, 0.25038669783359574)]

In [80]:
sorted(similarity[0], reverse=True)

[1.0000000000000002,
 0.28676966733820225,
 0.26901379342448517,
 0.2605130246476754,
 0.255608593705383,
 0.25038669783359574,
 0.24511108480187255,
 0.24455799402225922,
 0.2367785320221084,
 0.23179316248638276,
 0.23174488732966075,
 0.2278389747471728,
 0.2252817784447915,
 0.21853668936906193,
 0.21239769762143662,
 0.2108663315950723,
 0.2105263157894737,
 0.20443988269091456,
 0.20437977982832192,
 0.20395079136182276,
 0.2029530274475215,
 0.2029530274475215,
 0.20277677641345318,
 0.2024645717996314,
 0.2020475485519274,
 0.1979082783981174,
 0.19767387315371682,
 0.1976738731537168,
 0.19672236884115843,
 0.19252140716412977,
 0.19134594929397597,
 0.19088542889273336,
 0.19088542889273336,
 0.19007487139298027,
 0.1892994097121204,
 0.18731716231633883,
 0.1873171623163388,
 0.18693292157876878,
 0.1860807318911967,
 0.18394180184548975,
 0.18394180184548975,
 0.1813690625275029,
 0.18074256993863339,
 0.17996850826633903,
 0.17954621161490197,
 0.1777046633277277,
 0.177343107178349,
 0.17699808135119718,
 0.17521916101261562,
 0.17521916101261562,
 0.17521916101261562,
 0.1748149640244195,
 0.17316974359835272,
 0.17292861596651865,
 0.1711905958155815,
 0.1711905958155815,
 0.17040572913692198,
 0.16943474841747155,
 0.1675415633166782,
 0.16742770563222897,
 0.16742770563222897,
 0.16692446522239718,
 0.16563698349810535,
 0.16452254913212452,
 0.16426202236672155,
 0.16222142113076254,
 0.16122923187750418,
 0.16059101370939324,
 0.15907119074394446,
 0.15907119074394446,
 0.15789473684210528,
 0.15737789507292674,
 0.15609763526361567,
 0.15511334686589626,
 0.1540171257313038,
 0.15389675281277312,
 0.15389675281277312,
 0.152008377581442,
 0.15018785229652767,
 0.15018785229652767,
 0.15018785229652765,
 0.14843120879858804,
 0.14843120879858804,
 0.14808721943977307,
 0.14673479641335554,
 0.14659886790209342,
 0.14601068654819693,
 0.14567913668701626,
 0.14567913668701626,
 0.14509525002200235,
 0.14509525002200235,
 0.14509525002200233,
 0.14421498760030763,
 0.1442149876003076,
 0.14350946197048198,
 0.14350946197048198,
 0.1433848336691011,
 0.1433848336691011,
 0.1433848336691011,
 0.1419745572840903,
 0.1419745572840903,
 0.14159846508095775,
 0.14159846508095775,
 0.1411956236812263,
 0.1411956236812263,
 0.1411956236812263,
 0.1411956236812263,
 0.14048787173725413,
 0.13977653617040256,
 0.1391037210186643,
 0.1391037210186643,
 0.13872950617564817,
 0.13834289277321493,
 0.13834289277321493,
 0.13834289277321493,
 0.13834289277321493,
 0.13710212427677043,
 0.13710212427677043,
 0.13710212427677043,
 0.13710212427677043,
 0.13629325512727639,
 0.13530201829834768,
 0.13530201829834768,
 0.13530201829834768,
 0.13530201829834768,
 0.13530201829834768,
 0.13518451760896877,
 0.13497638119975428,
 0.13476498501489081,
 0.13369695534647594,
 0.13369695534647594,
 0.13369695534647594,
 0.13334518676566626,
 0.13334518676566626,
 0.1324532357065044,
 0.1324532357065044,
 0.1324532357065044,
 0.13157894736842107,
 0.13124359177794215,
 0.12988108336653278,
 0.12988108336653278,
 0.12988108336653278,
 0.12977713690461004,
 0.12977713690461004,
 0.12977713690461004,
 0.12892051277806202,
 0.12824729401064427,
 0.12824729401064427,
 0.12824729401064427,
 0.12824729401064427,
 0.12824729401064427,
 0.12824729401064427,
 0.12725695259515557,
 0.12725695259515557,
 0.12725695259515557,
 0.126673647984535,
 0.12565617248750865,
 0.12565617248750865,
 0.12515654358043973,
 0.12515654358043973,
 0.12515654358043973,
 0.12515654358043973,
 0.12487810821089254,
 0.12487810821089254,
 0.12487810821089254,
 0.12487810821089254,
 0.12462194771917919,
 0.12361284651454937,
 0.12262786789699316,
 0.12262786789699316,
 0.12262786789699313,
 0.12227899701112963,
 0.12227899701112963,
 0.12227899701112963,
 0.12166606584807191,
 0.12166606584807191,
 0.12166606584807191,
 0.12072654548783007,
 0.1204950466257556,
 0.1204950466257556,
 0.1204950466257556,
 0.1204950466257556,
 0.1204950466257556,
 0.11980845957463077,
 0.11959121830873498,
 0.11959121830873498,
 0.11959121830873498,
 0.11959121830873498,
 0.11846977555181847,
 0.11846977555181847,
 0.11846977555181847,
 0.11846977555181847,
 0.11846977555181847,
 0.11803342130469506,
 0.11803342130469505,
 0.11803342130469505,
 0.11803342130469505,
 0.11803342130469505,
 0.11712303424679457,
 0.11707322644771176,
 0.11707322644771176,
 0.11707322644771176,
 0.11707322644771176,
 0.11707322644771176,
 0.116543309349613,
 0.116543309349613,
 0.116543309349613,
 0.116543309349613,
 0.1163350101494222,
 0.11587244366483038,
 0.11551284429847784,
 0.11506355109724453,
 0.1147078669352809,
 0.1147078669352809,
 0.11470786693528087,
 0.11470786693528087,
 0.1141270638770543,
 0.11357771260606365,
 0.11357771260606365,
 0.11295649894498103,
 0.11295649894498103,
 0.1124803176664619,
 0.1124803176664619,
 0.1124803176664619,
 0.11243619908556624,
 0.11239029738980327,
 0.11164843913471803,
 0.11164843913471803,
 0.11164843913471803,
 0.11164843913471803,
 0.11141412945539662,
 0.11141412945539662,
 0.11141412945539661,
 0.11128297681493143,
 0.11128297681493143,
 0.11128297681493143,
 0.11128297681493143,
 0.11092107999698035,
 0.11092107999698035,
 0.11037769642208699,
 0.11020775375559676,
 0.11020775375559674,
 0.10968169942141637,
 0.10968169942141635,
 0.10968169942141635,
 0.10968169942141635,
 0.10968169942141635,
 0.10968169942141635,
 0.10968169942141635,
 0.10936965981495178,
 0.10882143751650175,
 0.10882143751650175,
 0.10882143751650175,
 0.10882143751650175,
 0.10876595882948199,
 0.10838874619051501,
 0.10838874619051501,
 0.10838874619051501,
 0.108388746190515,
 0.10814761408717502,
 0.10814761408717502,
 0.10814761408717502,
 0.1074861545850028,
 0.10743376064838502,
 0.1068366854693644,
 0.106676149412533,
 0.106676149412533,
 0.106676149412533,
 0.10650358071057624,
 0.10650358071057624,
 0.10619884881071831,
 0.10619884881071831,
 0.10619884881071831,
 0.10619884881071831,
 0.10619884881071831,
 0.10619884881071831,
 0.10559715077387793,
 0.10559715077387793,
 0.10559715077387793,
 0.10526315789473685,
 0.10526315789473685,
 0.10526315789473685,
 0.10526315789473685,
 0.10471347707292386,
 0.10390486669322622,
 0.10390486669322622,
 0.10390486669322622,
 0.10390486669322622,
 0.10390486669322622,
 0.10390486669322622,
 0.10390486669322622,
 0.10385162309931599,
 0.10385162309931599,
 0.1037571695799112,
 0.1037571695799112,
 0.1037571695799112,
 0.1037571695799112,
 0.1037571695799112,
 0.1037571695799112,
 0.1037571695799112,
 0.1037571695799112,
 0.1037571695799112,
 0.10301070542879115,
 0.10259783520851541,
 0.10259783520851541,
 0.10259783520851541,
 0.10259783520851541,
 0.10259783520851541,
 0.10259783520851541,
 0.10259783520851541,
 0.10218988991416095,
 0.10147651372376076,
 0.10147651372376076,
 0.10147651372376076,
 0.10138838820672659,
 0.101338918387628,
 0.101338918387628,
 0.10133891838762799,
 0.10060545457319173,
 0.10060545457319173,
 0.10060545457319173,
 0.10012523486435178,
 0.10012523486435178,
 0.10012523486435178,
 0.10012523486435178,
 0.10012523486435178,
 0.10012523486435178,
 0.09933992677987831,
 0.09933992677987831,
 0.09933992677987831,
 0.09933992677987831,
 0.09933992677987831,
 0.09933992677987831,
 0.09933992677987831,
 0.09933992677987831,
 0.09933992677987831,
 0.09933992677987831,
 0.09933992677987831,
 0.09933992677987831,
 0.09909250441117726,
 0.09909250441117726,
 0.0989541391990587,
 0.0989541391990587,
 0.0989541391990587,
 0.0989541391990587,
 0.0989541391990587,
 0.0989541391990587,
 0.09836118442057921,
 0.0978231976089037,
 0.0978231976089037,
 0.0978231976089037,
 0.0978231976089037,
 0.0978231976089037,
 0.0978231976089037,
 0.0978231976089037,
 0.0978231976089037,
 0.09733285267845754,
 0.09733285267845754,
 0.09733285267845754,
 0.09733285267845754,
 0.09733285267845754,
 0.09733285267845754,
 0.09733285267845754,
 0.09733285267845754,
 0.09733285267845754,
 0.09733285267845754,
 0.09733285267845754,
 0.0967301666813349,
 0.0967301666813349,
 0.09567297464698798,
 0.09567297464698798,
 0.09567297464698798,
 0.09567297464698798,
 0.09558988911273408,
 0.09544271444636668,
 0.09544271444636668,
 0.09544271444636668,
 0.09544271444636668,
 0.09544271444636668,
 0.09493290614465533,
 0.09464970485606021,
 0.09464970485606021,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816939,
 0.09269795493186431,
 0.09269795493186431,
 0.09269795493186431,
 0.09269795493186431,
 0.09269795493186431,
 0.09269795493186431,
 0.09269795493186431,
 0.09269795493186431,
 0.09269795493186431,
 0.09243423333081695,
 0.09197090092274487,
 0.09197090092274487,
 0.09197090092274487,
 0.09197090092274487,
 0.09197090092274487,
 0.09197090092274487,
 0.09197090092274487,
 0.09183979479633063,
 0.09183979479633063,
 0.09125667909262308,
 0.09125667909262308,
 0.09086217008485092,
 0.09086217008485092,
 0.09086217008485092,
 0.09086217008485092,
 0.09086217008485092,
 0.09086217008485092,
 0.09037128496931669,
 0.09037128496931669,
 0.09037128496931669,
 0.09037128496931669,
 0.09037128496931669,
 0.09037128496931669,
 0.09037128496931669,
 0.09037128496931669,
 0.09037128496931669,
 0.08998425413316952,
 0.08998425413316952,
 0.08998425413316952,
 0.08998425413316952,
 0.08998425413316952,
 0.08998425413316952,
 0.08998425413316952,
 0.08998425413316952,
 0.08998425413316952,
 0.08977310580745099,
 0.0891313035643173,
 0.08903057122447033,
 0.08885233166386385,
 0.08885233166386385,
 0.08885233166386385,
 0.08885233166386385,
 0.08885233166386385,
 0.08885233166386385,
 0.08830215713766959,
 0.08830215713766959,
 0.08830215713766959,
 0.08830215713766959,
 0.08830215713766959,
 0.08830215713766959,
 0.08830215713766959,
 0.08830215713766959,
 0.08797691788472335,
 0.08749572785196143,
 0.08749572785196143,
 0.08746392856766495,
 0.08740748201220976,
 0.08740748201220976,
 0.08740748201220976,
 0.08740748201220976,
 0.08740748201220976,
 0.08740748201220976,
 0.08740748201220976,
 0.08740748201220976,
 0.08740748201220976,
 0.08740748201220976,
 0.08671099695241201,
 0.08671099695241201,
 0.08671099695241201,
 0.08671099695241201,
 0.08671099695241201,
 0.08671099695241201,
 0.08671099695241201,
 0.08671099695241201,
 0.08603090020146065,
 0.08603090020146065,
 0.08603090020146065,
 0.08603090020146065,
 0.08603090020146065,
 0.08603090020146065,
 0.08603090020146065,
 0.08594700851870801,
 0.08594700851870801,
 0.08594700851870801,
 0.08520286456846099,
 0.08520286456846099,
 0.08471737420873576,
 0.08471737420873576,
 0.08471737420873576,
 0.08471737420873576,
 0.08471737420873576,
 0.08471737420873576,
 0.08471737420873576,
 0.08447772061910234,
 0.08447772061910234,
 0.08447772061910234,
 0.08447772061910234,
 0.08447772061910234,
 0.0837707816583391,
 0.0837707816583391,
 0.0837707816583391,
 0.0837707816583391,
 0.0837707816583391,
 0.0837707816583391,
 0.0837707816583391,
 0.0837707816583391,
 0.08346223261119858,
 0.08346223261119858,
 0.08346223261119858,
 0.08346223261119858,
 0.08346223261119858,
 0.08346223261119858,
 0.08346223261119858,
 0.08321783316232578,
 0.0830812984794528,
 0.0830812984794528,
 0.0830812984794528,
 0.08240856434303293,
 0.08240856434303293,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08175191193132876,
 0.08175191193132876,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08048436365855338,
 0.08000711205939975,
 0.08000711205939975,
 0.08000711205939975,
 0.08000711205939975,
 0.08000711205939975,
 0.08000711205939975,
 0.08000711205939975,
 0.08000711205939975,
 0.08000711205939975,
 0.07992075789278003,
 0.07987230638308718,
 0.07987230638308718,
 0.07987230638308718,
 0.07987230638308718,
 0.07987230638308718,
 0.0792740035289418,
 0.07894736842105264,
 0.07894736842105264,
 0.07894736842105264,
 0.07894736842105264,
 0.07894736842105264,
 0.07894736842105264,
 0.07894736842105264,
 0.07894736842105264,
 0.07894736842105264,
 0.07878168645790681,
 0.07868894753646337,
 0.07868894753646337,
 0.07868894753646337,
 0.07868894753646337,
 0.07868894753646337,
 0.07868894753646337,
 0.07868894753646337,
 0.07868894753646337,
 0.07868894753646337,
 0.07843304784240032,
 0.0781166566864507,
 0.0781166566864507,
 0.07792865001991967,
 0.07792865001991967,
 0.07792865001991967,
 0.07792865001991967,
 0.07792865001991967,
 0.07792865001991967,
 0.07792865001991967,
 0.07792865001991967,
 0.07792865001991967,
 0.07792865001991967,
 0.07755667343294813,
 0.07755667343294813,
 0.0770085628656519,
 0.07694837640638656,
 0.07694837640638656,
 0.07694837640638656,
 0.07694837640638656,
 0.07694837640638656,
 0.07694837640638656,
 0.07694837640638656,
 0.07694837640638656,
 0.07694837640638656,
 0.07694837640638656,
 0.07694837640638656,
 0.07647191129018727,
 0.07647191129018727,
 0.07647191129018727,
 0.07647191129018727,
 0.07647191129018727,
 0.07647191129018727,
 0.07647191129018727,
 0.07647191129018727,
 0.07647191129018727,
 0.07647191129018727,
 0.076004188790721,
 0.076004188790721,
 0.076004188790721,
 0.076004188790721,
 0.076004188790721,
 0.076004188790721,
 0.076004188790721,
 0.076004188790721,
 0.076004188790721,
 0.076004188790721,
 0.07594632491572426,
 0.07543142864047142,
 0.07530940414109724,
 0.07509392614826384,
 0.07509392614826384,
 0.07509392614826384,
 0.07509392614826384,
 0.07509392614826384,
 0.07509392614826384,
 0.07509392614826384,
 0.07509392614826384,
 0.07509392614826384,
 0.07509392614826384,
 0.07509392614826384,
 0.07509392614826384,
 0.07492686492653551,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07421560439929402,
 0.07421560439929402,
 0.07421560439929402,
 0.07421560439929402,
 0.07421560439929402,
 0.07394738666465357,
 0.07394738666465357,
 0.07394738666465357,
 0.0734718358370645,
 0.0734718358370645,
 0.07336739820667779,
 0.07336739820667779,
 0.07336739820667779,
 0.07336739820667779,
 0.07336739820667779,
 0.07336739820667779,
 0.07336739820667779,
 0.07336739820667777,
 0.07336739820667777,
 0.07254762501100118,
 0.07254762501100118,
 0.07254762501100118,
 0.07254762501100118,
 0.07254762501100118,
 0.07254762501100118,
 0.07254762501100118,
 0.07254762501100118,
 0.07254762501100118,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07209840939145001,
 0.07209840939145001,
 0.07175473098524099,
 0.07175473098524099,
 0.07175473098524099,
 0.07175473098524099,
 0.07175473098524099,
 0.07175473098524099,
 0.07175473098524099,
 0.07175473098524099,
 0.07175473098524099,
 0.07175473098524099,
 0.07175473098524099,
 0.07175473098524099,
 0.07175473098524099,
 0.07098727864204515,
 0.07098727864204515,
 0.07098727864204515,
 0.07098727864204515,
 0.07098727864204515,
 0.07098727864204515,
 0.07098727864204515,
 0.07098727864204515,
 0.07098727864204515,
 0.07098727864204515,
 0.07098727864204515,
 0.07098727864204515,
 0.07079923254047887,
 0.07079923254047887,
 0.07079923254047887,
 0.07079923254047887,
 0.07079923254047887,
 0.07079923254047887,
 0.07079923254047887,
 0.07038153430777869,
 0.07038153430777869,
 0.07024393586862707,
 0.07024393586862707,
 0.07024393586862707,
 0.06952346619889824,
 0.06952346619889824,
 0.06952346619889824,
 0.06952346619889824,
 0.06952346619889824,
 0.06952346619889824,
 0.06952346619889824,
 0.06952346619889824,
 0.06952346619889824,
 0.06952346619889824,
 0.06917144638660747,
 0.06917144638660747,
 0.06917144638660747,
 0.06917144638660747,
 0.06917144638660747,
 0.06882472016116853,
 0.06882472016116853,
 0.06882472016116853,
 0.06882472016116853,
 0.06882472016116853,
 0.06882472016116853,
 0.06882472016116853,
 0.06814662756363819,
 0.06814662756363819,
 0.06814662756363819,
 0.06814662756363819,
 0.06814662756363819,
 0.06814662756363819,
 0.06814662756363819,
 0.06814662756363819,
 0.06814662756363819,
 0.06814662756363819,
 0.06814662756363819,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06748819059987714,
 0.06748819059987714,
 0.06748819059987714,
 0.06748819059987714,
 0.06748819059987714,
 0.06748819059987714,
 0.0672863110252489,
 0.06684847767323797,
 0.06684847767323797,
 0.06684847767323797,
 0.06684847767323797,
 0.06657426652986062,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.06622661785325219,
 0.06622661785325219,
 0.06622661785325219,
 0.06622661785325219,
 0.06622661785325219,
 0.06622661785325219,
 0.06622661785325219,
 0.06622661785325219,
 0.06622661785325219,
 0.06622661785325219,
 0.06578947368421054,
 0.06562179588897107,
 0.06562179588897107,
 0.06562179588897107,
 0.06562179588897107,
 0.06562179588897107,
 0.06562179588897107,
 0.06562179588897107,
 0.06554735253444621,
 0.06521546507260247,
 0.065033247714309,
 0.065033247714309,
 0.065033247714309,
 0.065033247714309,
 0.065033247714309,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06446025638903101,
 0.06446025638903101,
 0.06446025638903101,
 0.06446025638903101,
 0.06446025638903101,
 0.06424925662032356,
 0.06390214842634574,
 0.06390214842634574,
 0.06390214842634574,
 0.06390214842634574,
 0.06390214842634574,
 0.06390214842634574,
 0.06362847629757779,
 0.06362847629757779,
 0.06362847629757779,
 0.06362847629757779,
 0.06362847629757779,
 0.06362847629757779,
 0.06362847629757779,
 0.06362847629757779,
 0.06362847629757779,
 0.06362847629757779,
 0.06362847629757779,

In [83]:
def recommend(movie):
  movie_index = new_df[new_df['title']==movie].index[0]
  distances = similarity[movie_index]
  movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x:x[1])[1:6]

  for i in movies_list:
    print(new_df.iloc[i[0]].title)

In [86]:
recommend('Batman Returns')

The Dark Knight
Batman
The Dark Knight Rises
Batman
Batman Forever

In [87]:
import pickle

In [90]:
pickle.dump(new_df.to_dict(), open('movies_dict.pkl','wb'))

In [89]:
new_df['title'].values

array(['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre',
       ..., 'Signed, Sealed, Delivered', 'Shanghai Calling',
       'My Date with Drew'], dtype=object)

In [91]:
pickle.dump(similarity, open('similarity.pkl', 'wb'))